#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# Wrike Clone — Production Deployment Script
# Target: $0/month stack (Supabase + Render + Vercel)
# ──────────────────────────────────────────────────────────────
# Prerequisites:
#   1. Supabase account (https://supabase.com)
#   2. Render account (https://render.com)
#   3. Vercel account (https://vercel.com)
#   4. GitHub repo with your code pushed
# ──────────────────────────────────────────────────────────────

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

echo "=============================================="
echo "  Wrike Clone — Production Deployment Guide"
echo "  Target: Supabase + Render + Vercel (Free)"
echo "=============================================="
echo ""

# ── Step 1: Supabase (Database) ─────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  STEP 1: Set up Supabase PostgreSQL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  a. Go to https://supabase.com and create a project"
echo "  b. Once created, go to Project Settings → Database"
echo "  c. Copy the Connection Pooler URI (port 6543, transaction mode)"
echo "     This will be your DATABASE_URL"
echo "  d. Copy the Direct Connection URI (port 5432)"
echo "     This will be your MIGRATE_DATABASE_URL"
echo "  e. Enable SSL: go to Project Settings → Database → SSL"
echo ""
echo "  Then run migrations against the DIRECT URI:"
echo ""
echo "    MIGRATE_DATABASE_URL=\"postgresql://...:5432/postgres\" \\"
echo "      DB_SSL=true \\"
echo "      npx knex migrate:latest --knexfile packages/backend/src/database/knexfile.ts"
echo ""
echo "  Seed initial data:"
echo ""
echo "    npx ts-node scripts/seed.ts"
echo ""

# ── Step 2: Render (Backend API) ────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  STEP 2: Deploy Backend to Render"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  a. Go to https://dashboard.render.com/select-repo?type=web"
echo "  b. Connect your GitHub repository"
echo "  c. Use these settings (or use render.yaml blueprint):"
echo ""
echo "     ┌──────────────────────────────────────────────┐"
echo "     │ Name:           wrike-clone-api              │"
echo "     │ Runtime:        Node                         │"
echo "     │ Build Command:  npm ci && npm run build \\    │"
echo "     │                -w packages/shared &&         │"
echo "     │                npm run build -w packages/    │"
echo "     │                backend                       │"
echo "     │ Start Command:  node packages/backend/       │"
echo "     │                dist/main.js                  │"
echo "     │ Health Path:   /api/v1/health                │"
echo "     │ Plan:          Free                          │"
echo "     └──────────────────────────────────────────────┘"
echo ""
echo "  d. Add Environment Variables:"
echo ""
echo "     DATABASE_URL=<Supabase pooler URI:6543>"
echo "     DB_SSL=true"
echo "     JWT_SECRET=<run: openssl rand -hex 32>"
echo "     CORS_ORIGINS=https://<your-app>.vercel.app"
echo "     DEFAULT_TENANT_SLUG=my-company"
echo "     NODE_ENV=production"
echo "     ALLOW_PUBLIC_REGISTRATION=false"
echo "     SETUP_KEY=<run: openssl rand -hex 16>"
echo ""
echo "  e. Deploy! Render will build and start the API."
echo "     Note: Free tier sleeps after 15 min idle."
echo ""

# ── Step 3: Vercel (Frontend SPA) ──────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  STEP 3: Deploy Frontend to Vercel"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  a. Go to https://vercel.com/new"
echo "  b. Import your GitHub repository"
echo "  c. Use these settings:"
echo ""
echo "     ┌──────────────────────────────────────────────┐"
echo "     │ Framework:    Vite                           │"
echo "     │ Root Dir:     packages/frontend              │"
echo "     │ Build:        npm ci \\                      │"
echo "     │              && npm run build \\             │"
echo "     │              -w packages/shared \\           │"
echo "     │              && npm run build \\             │"
echo "     │              -w packages/frontend            │"
echo "     │ Output Dir:   packages/frontend/dist         │"
echo "     └──────────────────────────────────────────────┘"
echo ""
echo "  d. Add Environment Variable:"
echo "     VITE_API_BASE_URL=https://<your-api>.onrender.com/api/v1"
echo ""
echo "  e. Deploy! Your app will be live at:"
echo "     https://<your-app>.vercel.app"
echo ""

# ── Step 4: Post-deployment ─────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  STEP 4: Post-Deployment Checklist"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  □ Verify health endpoint: https://<api>.onrender.com/api/v1/health"
echo "  □ Update CORS_ORIGINS on Render to match your Vercel domain"
echo "  □ Set up Uptime pinger (cron-job.org):"
echo "     → Create job: GET https://<api>.onrender.com/api/v1/health"
echo "     → Every 10 minutes during work hours"
echo "     → This prevents Render's free tier from sleeping"
echo ""
echo "  □ First login:"
echo "     → Go to https://<app>.vercel.app"
echo "     → Login with the seeded admin credentials"
echo "     → Change the temporary password when prompted"
echo ""
echo "  □ Security:"
echo "     → Rotate the seeded admin password immediately"
echo "     → Keep JWT_SECRET, SETUP_KEY, and DB password safe"
echo "     → Verify the admin slug field is hidden (DEFAULT_TENANT_SLUG works)"
echo ""

echo "=============================================="
echo "  Deployment Guide Complete!"
echo "=============================================="
echo ""
echo "  Need help? Check the docs:"
echo "  - Docs:      docs/WRIKE_CLONE_ARCHITECTURE.md"
echo "  - Blueprint: docs/PRODUCTION_READINESS_BLUEPRINT.md"
echo ""
